version: '3.4'

services:
  server1:
    image: 'crappy-web-server:$VERSION'
    restart: always
    deploy:
      replicas: 2
    environment:
      - CLIENT_ID=0
    ports:
      - '3000:3000'

  server2:
    image: 'crappy-web-server:$VERSION'
    restart: always
    deploy:
      replicas: 2
    environment:
      - CLIENT_ID=1
    ports:
      - '3001:3000'

  server3:
    image: 'crappy-web-server:$VERSION'
    restart: always
    deploy:
      replicas: 2
    environment:
      - CLIENT_ID=2
    ports:
      - '3002:3000'
