{{- range $key, $val := .Values.clients }}
apiVersion: batch/v1
kind: Job
metadata:
  name: crappy-migrations-{{ $val.id }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "10"
spec:
  template:
    spec:
      containers:
      - name: crappy-migrations-{{ $val.id }}
        image: localhost:5000/crappy-server:{{$.Values.versions.crappyServer}}
        command: ["sleep",  "30"]
      restartPolicy: Never
---
{{- end }}